language: python
python:
    - "2.7"
    - "3.4"
before_install:
    - "pip install -U pip"
    - "sudo apt-get update -qq"
    - "sudo apt-get install redis-server"
    - "sudo service redis-server start"
    - "pip install -r requirements/travis.txt"
script:
    - py.test tests --doctest-modules --pep8 msg/msg.py -v --cov-report term-missing --cov=msg/msg.py
after_success:
    - coveralls
